### ISSUE TITLE
Error when call ImbalancedDatasetSampler function

### ISSUE THREAD

**Issue by KhondokerIslam** [ufoym/imbalanced-dataset-sampler#16]
Following error occurred when creating this on dataloader

**Code**
`train_dataset = DataLoader(train_dataset, sampler=ImbalancedDatasetSampler(train_dataset), batch_size = BATCH_SIZE, 
                     drop_last=True
                     )`

**Error**

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-71-9f1792f30d37>", line 5, in <module>
    train_dataset = DataLoader(train_dataset, sampler=ImbalancedDatasetSampler(train_dataset),batch_size = BATCH_SIZE,
  File "/content/drive/My Drive/Research_Shanto/Shanto/Packages/imbalanced-dataset-sampler-master/torchsampler/imbalanced.py", line 32, in __init__
    label = self._get_label(dataset, idx)
  File "/content/drive/My Drive/Research_Shanto/Shanto/Packages/imbalanced-dataset-sampler-master/torchsampler/imbalanced.py", line 53, in _get_label
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 1823, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NotImplementedError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 1132, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 313, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 358, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.6/inspect.py", line 1490, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.6/inspect.py", line 1448, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.6/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.6/inspect.py", line 725, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/lib/python3.6/inspect.py", line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/usr/lib/python3.6/posixpath.py", line 383, in abspath
    cwd = os.getcwd()
OSError: [Errno 107] Transport endpoint is not connected

I really hope the community takes a note of it.

**Comment by joshwolff1** [comment]
I got this issue when not passing type torchvision.datasets.ImageFolder to the constructor for ImbalancedDatasetSampler
