### ISSUE TITLE
random_split support 

### ISSUE THREAD

**Issue by ZreXoc** [ufoym/imbalanced-dataset-sampler#59]
```
dataset = ImageFolder('./data/train', loader=imgLoader, transform=transforms.Compose([
        transforms.RandomResizedCrop(256),
        transforms.ToTensor()
    ]))

train_dataset, vali_dataset = random_split(dataset, [0.9,0.1])
train_loader = DataLoader(dataset=train_dataset, sampler=ImbalancedDatasetSampler(train_dataset) ,batch_size=BATCH_SIZE)
vali_dataset = DataLoader(dataset=vali_dataset,batch_size=BATCH_SIZE, shuffle=True)
```
Then I got:
```
Traceback (most recent call last):
  File "/home/xic/Documents/project/nailong-killer/train.py", line 46, in <module>
    train_loader = DataLoader(dataset=train_dataset, sampler=ImbalancedDatasetSampler(train_dataset) ,batch_size=BATCH_SIZE)
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xic/.conda/envs/ai/lib/python3.12/site-packages/torchsampler/imbalanced.py", line 38, in __init__
    df.index = self.indices
    ^^^^^^^^
  File "/home/xic/.conda/envs/ai/lib/python3.12/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/xic/.conda/envs/ai/lib/python3.12/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/xic/.conda/envs/ai/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/xic/.conda/envs/ai/lib/python3.12/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 2 elements, new values have 5306 elements
```

**Comment by intexcor** [comment]
ты смог это решить?

**Comment by intexcor** [comment]
https://github.com/ufoym/imbalanced-dataset-sampler/issues/36
решает проблему
